version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: AskifyAPI/Dockerfile
    ports:
      - "5244:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - postgres:connectionString=Server=195.150.230.208;Port=5432;Database=2023_piekielniak_jakub;Username=2023_piekielniak_jakub;Password=35228
    networks:
      - askify-network

  client:
    build:
      context: .
      dockerfile: AskifyClient/Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - api
    networks:
      - askify-network

networks:
  askify-network:
    driver: bridge